name: build openwrt for x86
run-name: ${{ github.actor }} is building an openwrt image for x86 platform 🚀
on:
  workflow_dispatch:
    inputs:
      ssh:
        description: ""
        required: false
        default: false

env:
  REPO_URL: https://github.com/coolsnowwolf/lede.git
  REPO_BRANCH: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: init environment
        run: |
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir

      - name: clone source code
        working-directory: /workdir
        run: |
          git clone $REPO_URL -b $REPO_BRANCH openwrt
          ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt      
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}