name: build openwrt for x86
run-name: ${{ github.actor }} is building an openwrt image for x86 platform 🚀
on:
  workflow_dispatch:
    inputs:
      ssh:
        description: ""
        required: false
        default: false

env:
  REPO_URL: https://github.com/coolsnowwolf/lede.git
  REPO_BRANCH: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: clone source code
        run: |
          git clone $REPO_URL -b $REPO_BRANCH openwrt
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: SSH connection to Actions
        uses: quboqin/ssh2actions@main
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
